import AuthService from "./auth.service";
import AccountService from "./account.service";
import PasswordHistoryService from "./passwordHistory.service";
import StoreService from "./store.service";
import ChainService from "./chain.service";
import TaskService from "./task.service";
import SelectStoreService from "./selectStore.service";
import HelpService from "./help.service";
import DownloadService from "./download.service";
import NotifyService from "./notify.service";
import DashboardService from "./dashboard.service";
import UploadService from "./upload.service";
import GanttChartService from "./ganttChart.service";
import OTAService from "./ota.service";
import PlanAmountService from "./planAmount.service";

export const authService = new AuthService({});
export const accountService = new AccountService({});
export const chainService = new ChainService({});
export const passwordHistoryService = new PasswordHistoryService({});
export const storeService = new StoreService({});
export const taskService = new TaskService({});
export const selectStoreService = new SelectStoreService({});
export const helpService = new HelpService({});
export const downloadService = new DownloadService({});
export const notifyService = new NotifyService({});
export const dashboardService = new DashboardService({});
export const uploadService = new UploadService({});
export const ganttChartService = new GanttChartService({});
export const otaService = new OTAService({});
export const planAmountService = new PlanAmountService({});
