const actions = {
  GET_TASKS_REQUEST: "TASKS/GET_TASKS_REQUEST",
  GET_TASKS_SUCCESS: "TASKS/GET_TASKS_SUCCESS",
  GET_TASKS_ERROR: "TASKS/GET_TASKS_ERROR",

  GET_TASKS_METADATA_REQUEST: "TASKS/GET_TASKS_METADATA_REQUEST",
  GET_TASKS_METADATA_SUCCESS: "TASKS/GET_TASKS_METADATA_SUCCESS",
  GET_TASKS_METADATA_ERROR: "TASKS/GET_TASKS_METADATA_ERROR",

  GET_CHILD_TASKS_REQUEST: "TASKS/GET_CHILD_TASKS_REQUEST",
  GET_CHILD_TASKS_SUCCESS: "TASKS/GET_CHILD_TASKS_SUCCESS",
  GET_CHILD_TASKS_ERROR: "TASKS/GET_CHILD_TASKS_ERROR",

  GET_TASK_LOG_REQUEST: "GET_TASK_LOG_REQUEST",
  GET_TASK_LOG_SUCCESS: "GET_TASK_LOG_SUCCESS",
  GET_TASK_LOG_ERROR: "GET_TASK_LOG_ERROR",

  GET_TASKLOG_TASKS_REQUEST: "GET_TASKLOG_TASKS_REQUEST",
  GET_TASKLOG_TASKS_SUCCESS: "GET_TASKLOG_TASKS_SUCCESS",
  GET_TASKLOG_TASKS_ERROR: "GET_TASKLOG_TASKS_ERROR",

  RESET_TASK_STORE: "TASKS/RESET_TASK_STORE",

  LOGOUT_RESET_LIST_TASK_SEARCH: "LOGOUT_RESET_LIST_TASK_SEARCH",

  getTasks: (payload) => ({ type: actions.GET_TASKS_REQUEST, payload }),

  getTaskLog: (payload) => ({ type: actions.GET_TASK_LOG_REQUEST, payload }),

  getTasklogTasks: (payload) => ({
    type: actions.GET_TASKLOG_TASKS_REQUEST,
    payload,
  }),

  getChildTasks: (payload) => ({ type: actions.GET_CHILD_TASKS_REQUEST, payload }),

  getTasksMetaData: (payload) => ({
    type: actions.GET_TASKS_METADATA_REQUEST,
    payload,
  }),
};

export default actions;
