const actions = {
  GET_STORE_DETAIL_REQUEST: "STORE/GET_STORE_DETAIL_REQUEST",
  GET_STORE_DETAIL_SUCCESS: "STORE/GET_STORE_DETAIL_SUCCESS",
  GET_STORE_DETAIL_ERROR: "STORE/GET_STORE_DETAIL_ERROR",

  GET_STORE_METADATA_REQUEST: "STORE/GET_STORE_METADATA_REQUEST",
  GET_STORE_METADATA_SUCCESS: "STORE/GET_STORE_METADATA_SUCCESS",
  GET_STORE_METADATA_ERROR: "STORE/GET_STORE_METADATA_ERROR",

  ADD_STORE_REQUEST: "STORE/ADD_STORE_REQUEST",
  ADD_STORE_SUCCESS: "STORE/ADD_STORE_SUCCESS",
  ADD_STORE_ERROR: "STORE/ADD_STORE_ERROR",

  EDIT_STORE_REQUEST: "STORE/EDIT_STORE_REQUEST",
  EDIT_STORE_SUCCESS: "STORE/EDIT_STORE_SUCCESS",
  EDIT_STORE_ERROR: "STORE/EDIT_STORE_ERROR",

  RESET_STORE_ADD_EDIT_STORE: "STORE/RESET_STORE_ADD_EDIT_STORE",

  UPDATE_EXPIRED_REQUEST: "STORE/UPDATE_EXPIRED_REQUEST",
  UPDATE_EXPIRED_SUCCESS: "STORE/UPDATE_EXPIRED_SUCCESS",
  UPDATE_EXPIRED_ERROR: "STORE/UPDATE_EXPIRED_ERROR",

  getStoreDetail: (payload) => ({
    type: actions.GET_STORE_DETAIL_REQUEST,
    payload,
  }),

  getStoreMetadata: (payload) => ({
    type: actions.GET_STORE_METADATA_REQUEST,
    payload: payload,
  }),

  createStore: (payload) => ({
    type: actions.ADD_STORE_REQUEST,
    payload: payload,
  }),

  editStore: (payload) => ({
    type: actions.EDIT_STORE_REQUEST,
    payload: payload,
  }),

  updateExpired: (payload) => ({
    type: actions.UPDATE_EXPIRED_REQUEST,
    payload,
  }),
};

export default actions;
